name: 'Posts – YouTube'
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-youtube:
    name: Update this repo's README with latest videos from YouTube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCqOAioEETt5-cXQRZT0fqzA'
          commit_message: 'Updated readme with the latest Youtube videos'
          committer_username: André lademann
          committer_email: vergissberlin@googlemail.com
          max_post_count: 12
          date_format: "dd.mm.yyyy"
          readme_path: "profile/README.md"
